### ISSUE TITLE
下载好也npm  i以后，node app.js报错

### ISSUE THREAD

**Issue by wangtao666** [kliuj/local-ajax-api#5]
E:\local-ajax-api-master\jsonServer>node app
E:\local-ajax-api-master\jsonServer\app.js:32
console.log("Express server listening on port %d in %s mode", app.address().port
, app.settings.env);
                                                                           ^

TypeError: Cannot read property 'port' of null
    at Object.<anonymous> (E:\local-ajax-api-master\jsonServer\app.js:32:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by kliuj** [comment]
有可能是端口已经被占用了，手动修改一下  app.listen(3000) 为其他端口试试看？
